### ISSUE TITLE
mstpr-brainbot - Bridging native tokens are not possible

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-woofi-swap-judging#14]
mstpr-brainbot

high

# Bridging native tokens are not possible

## Summary
When bridging ETH the StargateRouter takes SGETH from the user but the WooFi contracts sends native ETH via msg.value, which the function will revert. 
## Vulnerability Detail
In WoofiCrosschainRouter contract if the bridged token is native token then the wrapped WETH is unwrapped and send to the router as "msg.value":
```solidity
if (srcInfos.bridgeToken == weth) {
            IWETH(weth).withdraw(bridgeAmount);
            msgValue += bridgeAmount;
        } else {
            TransferHelper.safeApprove(srcInfos.bridgeToken, sgInfo.sgRouter(), bridgeAmount);
        }

        stargateRouter.swap{value: msgValue}(
            dstInfos.chainId, // dst chain id
            sgInfo.sgPoolIds(sgInfo.sgChainIdLocal(), srcInfos.bridgeToken), // bridge token's pool id on src chain
            sgInfo.sgPoolIds(dstInfos.chainId, dstInfos.bridgeToken), // bridge token's pool id on dst chain
            payable(_msgSender()), // rebate address
            bridgeAmount, // swap amount on src chain
            dstMinBridgeAmount, // min received amount on dst chain
            obj, // config: dstGasForCall, dstAirdropNativeAmount, dstReceiveAirdropNativeTokenAddr
            dstWooCrossChainRouter, // smart contract to call on dst chain
            payload // payload to piggyback
        );
    } 
```

However, the StargateRouter contract expects SGETH tokens from the user when the "native" token is bridged:
```solidity
function swap(
        uint16 _dstChainId,
        uint256 _srcPoolId,
        uint256 _dstPoolId,
        address payable _refundAddress,
        uint256 _amountLD,
        uint256 _minAmountLD,
        lzTxObj memory _lzTxParams,
        bytes calldata _to,
        bytes calldata _payload
    ) external payable override nonReentrant {
       .
       .
       {
            s = pool.swap(_dstChainId, _dstPoolId, msg.sender, _amountLD, _minAmountLD, true);
            -> _safeTransferFrom(pool.token(), msg.sender, address(pool), _amountLD);
            c = pool.sendCredits(_dstChainId, _dstPoolId);
        }
        bridge.swap{value: msg.value}(_dstChainId, _srcPoolId, _dstPoolId, _refundAddress, c, s, _lzTxParams, _to, _payload);
    }
```

as we can see above, the pool.token() for native asset is the Stargate's SGETH token and the WoofiCrosschainRouter sends ether instead of that.
E.g:
https://etherscan.io/address/0x101816545F6bd2b1076434B54383a1E633390A2E#code
Hence, the bridging is impossible. 
## Impact
Users can't bridge with native assets
## Code Snippet
https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L249-L267

https://github.com/stargate-protocol/stargate/blob/c647a3a647fc693c38b16ef023c54e518b46e206/contracts/Router.sol#L107-L134
## Tool used

Manual Review

## Recommendation
Wrap the token to SGETH instead of sending native eth

Duplicate of #151

**Comment by 0xmer1in** [comment]
We used to wrap native ETH to SGETH before, but change to sending native ETH via msg.value because Stargate update the compose way, and now `stargateRouter` in `WooCrossChainRouterV4` is `StargateComposer` actually.

`StargateComposer` doc: https://stargateprotocol.gitbook.io/stargate/stargate-composability/stargatecomposer.sol#swap
