### ISSUE TITLE
klaus - WooRouterV2.externalSwap: Cannot use BNB(ERC20) because of zero value approvals

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-woofi-swap-judging#3]
klaus

medium

# WooRouterV2.externalSwap: Cannot use BNB(ERC20) because of zero value approvals

## Summary

The BNB token, which is supported in WOOFi, cannot approve by zero value, so `WooRouterV2.externalSwap` always fails.

## Vulnerability Detail

Currently, BNB token is supported by WOOFi. The BNB token exists as ERC20 on chains other than the BNB chain.  And ERC20 BNB tokens are not allowed to approve zero value.

[https://etherscan.io/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52#code#L94](https://etherscan.io/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52#code#L94)

```solidity
function approve(address _spender, uint256 _value) returns (bool success) {
@>  if (_value <= 0) throw; 
    allowance[msg.sender][_spender] = _value;
    return true;
}
```

In WooRouterV2.externalSwap, it calls the external DEX and try to approve zero value. However, if it is BNB, the transaction is always reverted and the externalSwap would not be possible.

```solidity
function _internalFallbackSwap(
    address approveTarget,
    address swapTarget,
    address fromToken,
    uint256 fromAmount,
    bytes calldata data
) private {
    require(isWhitelisted[approveTarget], "WooRouter: APPROVE_TARGET_NOT_ALLOWED");
    require(isWhitelisted[swapTarget], "WooRouter: SWAP_TARGET_NOT_ALLOWED");

    if (fromToken != ETH_PLACEHOLDER_ADDR) {
        TransferHelper.safeTransferFrom(fromToken, msg.sender, address(this), fromAmount);
        TransferHelper.safeApprove(fromToken, approveTarget, fromAmount);
@>      (bool success, ) = swapTarget.call{value: 0}(data);
@>      TransferHelper.safeApprove(fromToken, approveTarget, 0);
        require(success, "WooRouter: FALLBACK_SWAP_FAILED");
    } else {
        require(fromAmount <= msg.value, "WooRouter: fromAmount_INVALID");
        (bool success, ) = swapTarget.call{value: fromAmount}(data);
        require(success, "WooRouter: FALLBACK_SWAP_FAILED");
    }
}
```

[https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/WooRouterV2.sol#L252](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/WooRouterV2.sol#L252)

## Impact

Cannot do externalSwap using BNB.

## Code Snippet

[https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/WooRouterV2.sol#L252](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/WooRouterV2.sol#L252)

## Tool used

Manual Review

## Recommendation

Don't do zero value approval.

**Comment by fb-alexcq** [comment]
Bug in BNB token contract, which doesn't comply ERC20. Revoke is meant to be conduct with `approve(0)`.
