### ISSUE TITLE
Bandit - Migration of Quote Token Will Revert Due to Using Different BalanceOf

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-woofi-swap-judging#36]
Bandit

medium

# Migration of Quote Token Will Revert Due to Using Different BalanceOf

## Summary

Different `balance`/`balanceOf` used in `migrateToNewPool` makes the function not work (always revert).

## Vulnerability Detail

`WooPPV2#migrateToNewPool` approves `balance(token)` and then calls the `depositAll` in the new pool. `depositAll` uses `balanceOf(token)`, rather than `balance(token)`, and this will be the root cause of this issue writeup.

The difference between the two balance functions is that `balance` subtracts the `unclaimedFee` from the token balance. Therefore, when `unclaimedFee > 0`, then balance(token) is less than `balanceOf(token)`.

```solidity
function balance(address token) public view returns (uint256) {
        return token == quoteToken ? _rawBalance(token) - unclaimedFee : _rawBalance(token);
    }
```

During migration, the transfer attempt will revert due to insufficient approval as the approved amount (`balance`) is less than the attempted transfer amount (`balanceOf`). Even if `claimFee` is called before the migration, it only takes a single swap, either incidentally or via a malicious frontrunner to make the unclaimedFee go above 0 and therefore make the migration revert.

## Impact

Migration of quote tokens to a new pool will revert. Even if fees are claimed, a single swap could DOS a subsequent attempt at migration.

## Code Snippet

https://github.com/sherlock-audit/2024-03-woofi-swap/blob/main/WooPoolV2/contracts/WooPPV2.sol#L344

## Tool used

Manual Review

## Recommendation

Either of these solutions will work:

1. Use the same `balance` in `depositAll` and line `TransferHelper.safeApprove(token, newPool, bal);`

2. claim fee within the `MigrateToNewPool` function before the balance approvals and transfers.

**Comment by Banditx0x** [comment]
Escalate.

The suggestion to "manually" avoid this, requires the owner to be aware of this issue, then pause the entire protocol to migrate tokens. Additionally a user can simply make a swap after the fees are claimed and before the pause, then migration will fail.

It is not at all intended for the protocol to pause the entire protocol in order to do a simple migration of tokens. 

> "no one can do anything to stop this migration if you do the above."

1- Claim all the fees first
2- User frontruns pause with a swap

Protocol: ????

**Comment by sherlock-admin2** [comment]
> Escalate.
> 
> The suggestion to "manually" avoid this, requires the owner to be aware of this issue, then pause the entire protocol to migrate tokens. Additionally a user can simply make a swap after the fees are claimed and before the pause, then migration will fail.
> 
> It is not at all intended for the protocol to pause the entire protocol in order to do a simple migration of tokens. 
> 
> > "no one can do anything to stop this migration if you do the above."
> 
> 1- Claim all the fees first
> 2- User frontruns pause with a swap
> 
> Protocol: ????
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Banditx0x** [comment]
> Since `MigrateToNewPool` is admin-only method, we will definitely claim the fee before migrating.
> 
> BTW, cannot use `balance` in depositAll, since other admin EOA wallets are calling this method.

@fb-alexcq an alternative solution is to simply approve all tokens before the transfer (rather than only approving the balance) so the transfer will always succeed. Approvals can be reset to 0 after the transfer. This would not affect the transfer amount but would make it un-DOS-able.

**Comment by mstpr** [comment]
> Escalate.
> 
> The suggestion to "manually" avoid this, requires the owner to be aware of this issue, then pause the entire protocol to migrate tokens. Additionally a user can simply make a swap after the fees are claimed and before the pause, then migration will fail.
> 
> It is not at all intended for the protocol to pause the entire protocol in order to do a simple migration of tokens.
> 
> > "no one can do anything to stop this migration if you do the above."
> 
> 1- Claim all the fees first 2- User frontruns pause with a swap
> 
> Protocol: ????

3- Claim fee again
4- migrate
😃

**Comment by Banditx0x** [comment]
> 3- Claim fee agin

> 4- User makes a swap

DOSed again. There's no guaruntee that the migration happens before a user front-runs with a swap

**Comment by WangSecurity** [comment]
I still believe it should remain invalid due to reasons I commented above. About the escalation reasoning, I strongly agree with tapit and I don't think this issue is higher than Low, since it can be easily mitigated and looks to be a DoS of one block, but perpetual (which is considered a DOS of one block under Sherlock's rules).

**Comment by Czar102** [comment]
Can't the owner firstly pause, then claim fees? Or set the fees to 0, then claim all fees? That wouldn't even require pausing, right?

If that's true, I'm planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Yes, they can either pause or set the fees to 0 and migrate successfully.

**Comment by Czar102** [comment]
Result:
Low
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [banditx0x](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/36/#issuecomment-2039063670): rejected
