### ISSUE TITLE
Bandit - User Does not get Stargate Gas Refund When Going Through Widget

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-woofi-swap-judging#37]
Bandit

high

# User Does not get Stargate Gas Refund When Going Through Widget

## Summary

The stargate gas refund goes to the widget rather than the user who intiated the transaction and sent the gas.

## Vulnerability Detail

`WooCrossChainRouterV4#CrossSwap` passes calls `_bridgeByStargate` which in turn calls `stargateRouter#swap`, [passing in `msg.sender` as the `refundAddress` parameter](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/main/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L260).

The `refundAddress` is the address that gets sent the excess gate from stargate bridging. However, when `crossSwap` is called via the `WooCrossRouterForWidget`, the `msg.sender` is the `WooCrossRouterForWidget` contract, and NOT the user that originally called the function. Note that the ETH sent to the Widget Router is never attributed to the original user.

Therefore the gas refund will be sent to the CrossRouterForWidget rather than user, resulting in user losing their gas refund.

## Impact

Users will lose their gas refund on every transaction through the widget. Note that this applies not only for the widget, but any contract (so not an EOA) which will route through `WooCrossChainRouterV4`

## Code Snippet

https://github.com/sherlock-audit/2024-03-woofi-swap/blob/main/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L260

## Tool used

Manual Review

## Recommendation

In the `crossSwap` function add a `_refundReceiver` input parameter. This can be passed along to the stargate `swap` function rather than `payable(msgSender)`

Duplicate of #11

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/woonetwork/WooPoolV2/pull/112/commits/7306a2bf67a2a849feadb7e022d8508ea0f6f450

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
