### ISSUE TITLE
AuditorPraise - in WooCrossChainRouter.crossSwap() when doing swaps, WooRouter.externalSwap() and wooRouter.swap() were never called with msg.value. [DOS]

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-woofi-swap-judging#52]
AuditorPraise

high

# in WooCrossChainRouter.crossSwap() when doing swaps, WooRouter.externalSwap() and wooRouter.swap() were never called with msg.value. [DOS]

## Summary
There are checks in `WooRouter.externalSwap()` and `WooRouter.swap()` with msg.value but msg.value was never indicated when calling wooRouter.sol's swap functions.
## Vulnerability Detail
In crossSwap() whenever `srcInfos.fromToken == ETH_PLACEHOLDER_ADDR` 

1. if `srcInfos.fromToken != srcInfos.bridgeToken` an external swap is done via 1inch. 

The issue lies in the fact that in `WooRouter.externalSwap()`, inside `_internalFallbackSwap()` [this](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/main/WooPoolV2/contracts/WooRouterV2.sol#L255) check `require(fromAmount <= msg.value, "WooRouter: fromAmount_INVALID");`  will cause a revert as msg.value here will be 0 and `fromAmount` being a uint can never be < 0 and it won't be == 0.
```solidity
} else {
            require(fromAmount <= msg.value, "WooRouter: fromAmount_INVALID"); //@audit-issue msg.value will be 0
            (bool success, ) = swapTarget.call{value: fromAmount}(data);
            require(success, "WooRouter: FALLBACK_SWAP_FAILED");
        }
```
This issue here is that in crossSwap() function msg.value was never indicated when [calling](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/main/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L101-L110) `WooRouter.externalSwap()`.
```solidity
                    bridgeAmount = wooRouter.externalSwap(
                        src1inch.swapRouter,
                        src1inch.swapRouter,
                        srcInfos.fromToken,
                        srcInfos.bridgeToken,
                        srcInfos.fromAmount,
                        srcInfos.minBridgeAmount,
                        payable(address(this)),
                        src1inch.data
                    );
```

2. Same with swaps via woofi. Msg.value wasn't indicated when calling `wooRouter.swap()` 
```solidity
                    // swap via WOOFi
                    bridgeAmount = wooRouter.swap(
                        srcInfos.fromToken,
                        srcInfos.bridgeToken,
                        srcInfos.fromAmount,
                        srcInfos.minBridgeAmount,
                        payable(address(this)),
                        to
                    );
```

So whenever fromToken is ETH holder address, [this](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/main/WooPoolV2/contracts/WooRouterV2.sol#L132) check will cause a revert
```solidity

if (isFromETH) {
            require(fromAmount <= msg.value, "WooRouter: fromAmount_INVALID");// @audit-issue msgValue could be 0
            IWETH(WETH).deposit{value: msg.value}();
            TransferHelper.safeTransfer(WETH, address(wooPool), fromAmount);
        } else {
```
This is caused by the same reason as the other external swap, msg.value here will be 0 and `fromAmount` being a uint can never be < 0 and it won't be == 0

## Impact
crossSwap() will always revert at local swap by 1inch router and swap via WOOFi because of  the checks in `WooRouter.externalSwap()` and `WooRouter.swap()` i mentioned above as msg.value was never indicated when calling them functions.

## Code Snippet
https://github.com/sherlock-audit/2024-03-woofi-swap/blob/main/WooPoolV2/contracts/WooRouterV2.sol#L132

https://github.com/sherlock-audit/2024-03-woofi-swap/blob/main/WooPoolV2/contracts/WooRouterV2.sol#L255
## Tool used

Manual Review

## Recommendation
Specify msg.value when calling the 2 WooRouter.sol swap functions.
1. 
```solidity

if (src1inch.swapRouter != address(0)) {
                    // external swap via 1inch
- >>               bridgeAmount = wooRouter.externalSwap(//@audit-issue msg.value wasn't specified here.
                        src1inch.swapRouter,
                        src1inch.swapRouter,
                        srcInfos.fromToken,
                        srcInfos.bridgeToken,
                        srcInfos.fromAmount,
                        srcInfos.minBridgeAmount,
                        payable(address(this)),
                        src1inch.data
                    );
```

```solidity
if (src1inch.swapRouter != address(0)) {
                    // external swap via 1inch
+ >>               bridgeAmount = wooRouter.externalSwap{value: msgValue}(//@audit-ok msg.value is specified here.
                        src1inch.swapRouter,
                        src1inch.swapRouter,
                        srcInfos.fromToken,
                        srcInfos.bridgeToken,
                        srcInfos.fromAmount,
                        srcInfos.minBridgeAmount,
                        payable(address(this)),
                        src1inch.data
                    );

```

2. 

```solidity
 // swap via WOOFi
- >>                bridgeAmount = wooRouter.swap(//@audit-issue not called with msg.value
                        srcInfos.fromToken,
                        srcInfos.bridgeToken,
                        srcInfos.fromAmount,
                        srcInfos.minBridgeAmount,
                        payable(address(this)),
                        to
                    );

```

```solidity
 // swap via WOOFi
+ >>                bridgeAmount = wooRouter.swap{value: msgValue}(//@audit-ok called with msg.value
                        srcInfos.fromToken,
                        srcInfos.bridgeToken,
                        srcInfos.fromAmount,
                        srcInfos.minBridgeAmount,
                        payable(address(this)),
                        to
                    );

```

**Comment by AuditorPraise** [comment]
> 1 comment(s) were left on this issue during the judging contest.
> 
> **WangAudit** commented:
> 
> > if we call crossSwap with ETH as from token and msg.value; crossSwap wraps it into WETH and when we call swap on routers it's already WETH and not ETH

Hey, yes crossSwap wraps ETH into WETH BUT ETH is still maintained as `fromToken` when calling router

**Comment by WangSecurity** [comment]
@AuditorPraise but we change fromToken from ETH to WETH at the very start, no?

https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/WooRouterV2.sol#L127

Therefore, after it, every time we use fromToken, we use WETH, or I am missing something here?
