### ISSUE TITLE
yotov721 - External swap fee would also be applied to native swaps

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-woofi-swap-judging#64]
yotov721

medium

# External swap fee would also be applied to native swaps

## Summary
The protocol has two choices when it comes to swapping tokens - Native via WooFi pool or external. For external currently 1Inch is supported. There is no fee for native swaps , but there is a fee for external/1inch swaps. The problem is that the external fee is applied to an internal swap.

## Vulnerability Detail
The main idea of the protocol is **cross-chain swaps**: Ability to swap token A from chain X to token B from chain Y. This is achieved by first swapping token A for token C, bridging token C to chain Y and swapping token Y for token B. https://learn.woo.org/woofi/cross-chain-swaps

If cross chain swap is required LZ's stargate router is used to bridge the tokens. https://stargateprotocol.gitbook.io/stargate

Also according to docs the contract would be deployed to all chains (Arbitrum, Optimism, Base, Avalanche, BSC, Polygon PoS, Mantle, Fantom, Polygon zkEVM, zkSync, Linea) in order to handle the receive on the target chain. 

The receive is handled via the `WooCrossChainRouterV4::sgReceive` function, where the payload is decoded. It has separate logic for handling native token receives and ERC20 receives. 
In the handling of ERC20 tokens receives there are 2 scenarios 

1. no swap is required - token is swapped on source chain and just bridged over to the target chain
```javascript
if (toToken == bridgedToken) {
            TransferHelper.safeTransfer(bridgedToken, to, bridgedAmount);
```
2. the token is swapped on target chain - this can be done either by native or external/1inch swap. 

The external fee would apply to both external and native swaps as it is defined before the check for swap type.
```javascript
 // Deduct the external swap fee
            uint256 fee = (bridgedAmount * dstExternalFeeRate) / FEE_BASE;
@>            bridgedAmount -= fee;

            TransferHelper.safeApprove(bridgedToken, address(wooRouter), bridgedAmount);
@>            if (dst1inch.swapRouter != address(0)) {
                // 1Inch swap done here
@>           } else {
               // local swap done here
```

## Impact
The user gets charged fee without having to when swapping tokens

## Code Snippet
https://github.com/sherlock-audit/2024-03-woofi-swap/blob/main/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L413-L414

## Tool used
Manual Review

## Recommendation
Move the fee calculation inside the if block that checks if 1Inch swap router != address(0) so fees are applied only to external call swaps
```diff
      } else {
            // Deduct the external swap fee
-            uint256 fee = (bridgedAmount * dstExternalFeeRate) / FEE_BASE;
-            bridgedAmount -= fee;

            TransferHelper.safeApprove(bridgedToken, address(wooRouter), bridgedAmount);
            if (dst1inch.swapRouter != address(0)) {
+              uint256 fee = (bridgedAmount * dstExternalFeeRate) / FEE_BASE;
+              bridgedAmount -= fee;
                try
                    wooRouter.externalSwap(
                        dst1inch.swapRouter,
                        dst1inch.swapRouter,
                        bridgedToken,
                        toToken,
                        bridgedAmount,

```

Duplicate of #114

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/woonetwork/WooPoolV2/pull/112/commits/be8655bf5d9660684eff1e2c12ff5d140fddc474

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
