### ISSUE TITLE
hals - `WooCrossChainRouterV4._bridgeByStargate()` function : gas refund is sent to the wrong address if interacted with by a third-party via the widget contract

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-woofi-swap-judging#88]
hals

medium

# `WooCrossChainRouterV4._bridgeByStargate()` function : gas refund is sent to the wrong address if interacted with by a third-party via the widget contract

## Summary

Third party protocols can interact with woofi protocol via the widget contract, where any gas refunds are supposed to be sent to the address that initiated the call via the widget contract, but this address is set as the widget contract address, so the gas refund will be sent to the widget contract address instead of the address that initiated the call.

## Vulnerability Detail

- Third party protocols can interact with woofi protocol via the widget contract to do cross-chain swapping where `WooCrossChainRouterV4.crossSwap()` function is called, then the call is processed via `stargateRouter` that uses layerZero for bridging messages from the source chain to the destination chain, where the bridged tokens are going to be received (after doing swap on the destination chain by the `stargateRouter`), and the transaction will be as follows:

1.  Third party protocols call widget contract to execute `crossSwap()`, which will invoke `WooCrossChainRouterV4.crossSwap()` function, where swapping on the source chain is done if required, then a stargate swap call is prepared by `_bridgeByStargate()`:

    ```javascript
    function crossSwap(
        uint256 refId,
        address payable to,
        SrcInfos memory srcInfos,
        DstInfos calldata dstInfos,
        Src1inch calldata src1inch,
        Dst1inch calldata dst1inch
    ) external payable whenNotPaused nonReentrant {
        //some code...
        _bridgeByStargate(refId, to, msgValue, bridgeAmount, srcInfos, dstInfos, dst1inch);
        //some code...
    }


        function _bridgeByStargate(
        uint256 refId,
        address payable to,
        uint256 msgValue,
        uint256 bridgeAmount,
        SrcInfos memory srcInfos,
        DstInfos calldata dstInfos,
        Dst1inch calldata dst1inch
    ) internal {
        //some code...
            stargateRouter.swap{value: msgValue}(
                dstInfos.chainId, // dst chain id
                sgInfo.sgPoolIds(sgInfo.sgChainIdLocal(), srcInfos.bridgeToken), // bridge token's pool id on src chain
                sgInfo.sgPoolIds(dstInfos.chainId, dstInfos.bridgeToken), // bridge token's pool id on dst chain
                payable(_msgSender()), // rebate address
                bridgeAmount, // swap amount on src chain
                dstMinBridgeAmount, // min received amount on dst chain
                obj, // config: dstGasForCall, dstAirdropNativeAmount, dstReceiveAirdropNativeTokenAddr
                dstWooCrossChainRouter, // smart contract to call on dst chain
                payload // payload to piggyback
            );

    }
    ```

    where [`stargateRouter.swap()`](https://github.com/stargate-protocol/stargate/blob/c647a3a647fc693c38b16ef023c54e518b46e206/contracts/Router.sol#L107C5-L134C6) function parameters are:

    ```javascript
            function swap(
                uint16 _dstChainId,
                uint256 _srcPoolId,
                uint256 _dstPoolId,
                address payable _refundAddress,
                uint256 _amountLD,
                uint256 _minAmountLD,
                lzTxObj memory _lzTxParams,
                bytes calldata _to,
                bytes calldata _payload
            ) external payable override nonReentrant {
                //some code...
            }
    ```

- As can be noticed; the 4th argument represents the refund address for excess gas, and this address is set as the `_msgSender()` of the `WooCrossChainRouterV4.crossSwap()` function, which is the [`WooCrossRouterForWidget`](https://github.com/woonetwork/WooPoolV2/blob/a99e13de1492c17a325fff6cddb3696cd7db7dc9/contracts/CrossChain/WooCrossRouterForWidget.sol#L133) contract address:

  ```javascript
  function crossSwap(
          address payable to,
          IWooCrossChainRouterV3.SrcInfos memory srcInfos,
          IWooCrossChainRouterV3.DstInfos memory dstInfos,
          IWooCrossChainRouterV3.Src1inch calldata src1inch,
          IWooCrossChainRouterV3.Dst1inch calldata dst1inch,
          FeeInfo calldata feeInfo
      ) external payable whenNotPaused nonReentrant {
      //some code...
          crossRouter.crossSwap{value: msgValue}(refId, to, srcInfos, dstInfos, src1inch, dst1inch);
      }
  ```

- But this refund address should be the address that has called `WooCrossRouterForWidget.crossSwap()` function who has paid for the transaction and not the widget contract address.

## Impact

This would result in addresses (3rd party protocol users) calling `WooCrossRouterForWidget.crossSwap()` to lose the residual gas from their layerzero bridging calls.

## Code Snippet

[WooCrossChainRouterV4.\_bridgeByStargate function](https://github.com/woonetwork/WooPoolV2/blob/a99e13de1492c17a325fff6cddb3696cd7db7dc9/contracts/CrossChain/WooCrossChainRouterV4.sol#L260C13)

```javascript
stargateRouter.swap{value: msgValue}(
            dstInfos.chainId, // dst chain id
            sgInfo.sgPoolIds(sgInfo.sgChainIdLocal(), srcInfos.bridgeToken), // bridge token's pool id on src chain
            sgInfo.sgPoolIds(dstInfos.chainId, dstInfos.bridgeToken), // bridge token's pool id on dst chain
            payable(_msgSender()), // rebate address
            bridgeAmount, // swap amount on src chain
            dstMinBridgeAmount, // min received amount on dst chain
            obj, // config: dstGasForCall, dstAirdropNativeAmount, dstReceiveAirdropNativeTokenAddr
            dstWooCrossChainRouter, // smart contract to call on dst chain
            payload // payload to piggyback
        );
```

## Tool used

Manual Review

## Recommendation

Update `WooCrossChainRouterV4.crossSwap()` function to receive the address of the gas refund receiver, and update `WooCrossChainRouterV4._bridgeByStargate()` to receive this address and set it as the refund address when calling `stargateRouter.swap(...)`.

Duplicate of #11

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/woonetwork/WooPoolV2/pull/112/commits/7306a2bf67a2a849feadb7e022d8508ea0f6f450

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
