### ISSUE TITLE
hals - `WooracleV2_2.decimals()` function returns a hardcoded wrong price decimals

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-woofi-swap-judging#90]
hals

high

# `WooracleV2_2.decimals()` function returns a hardcoded wrong price decimals

## Summary

`WooracleV2_2.decimals()` function returns a hardcoded wrong price decimals.

## Vulnerability Detail

- `WooracleV2_2.decimals()` function is called by the `WooPPV2.decimalInfo()` function when the amount of bought/sold assets are calculated, and to calculate the new price of the bought/sold base tokens:

  ```javascript
    function decimalInfo(address baseToken) public view returns (DecimalInfo memory) {
            return
                DecimalInfo({
                    priceDec: uint64(10) ** (IWooracleV2(wooracle).decimals(baseToken)), // 8
                    quoteDec: uint64(10) ** (IERC20Metadata(quoteToken).decimals()), // 18 or 6
                    baseDec: uint64(10) ** (IERC20Metadata(baseToken).decimals()) // 18 or 8
                });
        }
  ```

  and as can be noticed; `WooracleV2_2.decimals()` function assumes that the returned base token price is always in **8 decimals**:

  ```javascript
  function decimals(address) external pure override returns (uint8) {
          return 8;
      }
  ```

- By knowing that chainlink price feeds are going to be used to fetch the prices of the quote and base assets, and the `_cloPriceInQuote()` returns the price in **quote** decimals, where this returned price will be used later either to :

  - be used as a bound check for the manually saved base price
  - or using the returned chainlink price if the saved price is outdated and using chainlink price is preferred for that base token (when `!woFeasible && clo_preferred ` then use the `cloPrice`):

    ```javascript
        function _cloPriceInQuote(address _fromToken, address _toToken)
                internal
                view
                returns (uint256 refPrice, uint256 refTimestamp)
            {
                address baseOracle = clOracles[_fromToken].oracle;
                if (baseOracle == address(0)) {
                    return (0, 0);
                }
                address quoteOracle = clOracles[_toToken].oracle;
                uint8 quoteDecimal = clOracles[_toToken].decimal;

                (, int256 rawBaseRefPrice, , uint256 baseUpdatedAt, ) = AggregatorV3Interface(baseOracle).latestRoundData();
                (, int256 rawQuoteRefPrice, , uint256 quoteUpdatedAt, ) = AggregatorV3Interface(quoteOracle).latestRoundData();
                uint256 baseRefPrice = uint256(rawBaseRefPrice);
                uint256 quoteRefPrice = uint256(rawQuoteRefPrice);

                // NOTE: Assume wooracle token decimal is same as chainlink token decimal.
                uint256 ceoff = uint256(10)**quoteDecimal;
                refPrice = (baseRefPrice * ceoff) / quoteRefPrice;
                refTimestamp = baseUpdatedAt >= quoteUpdatedAt ? quoteUpdatedAt : baseUpdatedAt;
            }
    ```

**But where exactly does the returned decimals() doesn't match the actual price decimal?**
Let's look at the following example; knowing that the quote tokens are stable tokens such as USDC & USDT which have 6-decimals on some chains and 18 decimals on other chains (as in BNB smart chain):

1. The `WooracleV2_2` is deployed on BNB smart chain, where we have [USDC](https://bscscan.com/token/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d) as the quote token with 18-decimals, and [Binance-Peg Ethereum Token-ETH](https://bscscan.com/token/0x2170ed0880ac9a755fd29b2688956bd959f933f8) as a base token with 18-decimals.

2. In `_cloPriceInQuote()` function:

   - the `quoteOracle` is `USDC / USD` data feed with price returned in 8 decimals
   - and the `baseOracle` is `ETH / USD` data feed with price returned in 8 decimals

3. Now the `refPrice` will be returned in `quoteDecimal`; which is 18 decimals.

- So as can be noticed; if the `_cloPriceInQuote` returned price is consumed by the `WooPPV2` contract, then the price decimals are 18 not 8 decimals!

## Impact

- If we look at `WooPPV2._calcQuoteAmountSellBase()` function as an example, the calculated `gamma` will be larger than it's supposed to be (in our example it's larger by 1e10), and since this value is used to calculate the `quoteAmount` and the `newPrice`, then this will result in:

  ```javascript
  function _calcQuoteAmountSellBase(
          address baseToken,
          uint256 baseAmount,
          IWooracleV2.State memory state
      ) private view returns (uint256 quoteAmount, uint256 newPrice) {
      //...
          DecimalInfo memory decs = decimalInfo(baseToken);
      //...

            //! @audit-issue : (bAmount*e18) * (1e18) * coeff / (1e8 * 1e18) = bAmount*coeff*e10
            //! while it should be: (bAmount*e18) * (1e18) * coeff / (1e18 * 1e18) = bAmount*coeff
              gamma = (baseAmount * state.price * state.coeff) / decs.priceDec / decs.baseDec;
      //...
              quoteAmount =
                  (((baseAmount * state.price * decs.quoteDec) / decs.priceDec) *
                      (uint256(1e18) - gamma - state.spread)) /
                  1e18 /
                  decs.baseDec;
      //...
          // newPrice = oracle.price * (1 - k * oracle.price * baseAmount)
          newPrice = ((uint256(1e18) - gamma) * state.price) / 1e18;
      }
  ```

  - incorrect `quoteAmount` tokens, so the user will have incorrect amounts of quote tokens for his sold base:

  ```javascript
  quoteAmount =
    (((baseAmount * state.price * decs.quoteDec) / decs.priceDec) *
      (uint256(1e18) - gamma - state.spread)) /
    1e18 /
    decs.baseDec;
  ```

  - the `newPrice` of the bought base (that's sold by the user) will be reduced significantly:

  ```javascript
          // newPrice = oracle.price * (1 - k * oracle.price * baseAmount)
          newPrice = ((uint256(1e18) - gamma) * state.price) / 1e18;
      }
  ```

- Also if this is argued to be handled by increaing the `tokenInfos[baseToken].maxGamma` that the calculated gamma is checked against; this will not substitute as a solution as the `newPrice` of the base token will be decreased much higher than in other chains where USDC token has 6 decimals. This will result in base tokens prices having large decrepancies between chains.

## Code Snippet

[WooracleV2_2.decimals function](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/wooracle/WooracleV2_2.sol#L263C2-L265C6)

```javascript
  function decimals(address) external pure override returns (uint8) {
        return 8;
    }
```

## Tool used

Manual Review

## Recommendation

Update `WooracleV2_2.decimals()` function to return the correct price decimals; which is the decimals of the quote token.

**Comment by DevHals** [comment]
Escalate
this issue has been misjudged as it seesms clearly fromt the judge [comment](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/90#:~:text=WangAudit%20commented%3A,denominated%20in%20USD):
> WangAudit commented:
the decimals are set according to the chainlink's price feed (you can see in the function setQuoteToken) therefore; it will be indeed 8 decimals cause chainlinks price feeds have 8 decimals if denominated in USD

while this issue has nothing to do with the chainlink price decimals but with the **assumption that the calculated quote price by `_cloPriceInQuote()` will be always of 8 decimals** (as the calculated price decimal is returned by [`decimals()`](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/wooracle/WooracleV2_2.sol#L263C5-L265C6) function) that is mistakenly assumed to be compatible with the used quote tokens on every chain, 

I am quoting the step-by-step illustration that was demonstrated by this issue [here](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/90#:~:text=But%20where%20exactly,not%208%20decimals!), where it had been clearly shown that the calculated price would be in different decimals than the assumed **8** decimals :
> **But where exactly does the returned decimals() doesn't match the actual price decimal?**
Let's look at the following example; knowing that the quote tokens are stable tokens such as USDC & USDT which have 6-decimals on some chains and 18 decimals on other chains (as in BNB smart chain):  
>1. The `WooracleV2_2` is deployed on BNB smart chain, where we have [USDC](https://bscscan.com/token/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d) as the quote token with 18-decimals, and [Binance-Peg Ethereum Token-ETH](https://bscscan.com/token/0x2170ed0880ac9a755fd29b2688956bd959f933f8) as a base token with 18-decimals.
>
> 2. In `_cloPriceInQuote()` function:
  > - the `quoteOracle` is `USDC / USD` data feed with price returned in 8 decimals
  > - and the `baseOracle` is `ETH / USD` data feed with price returned in 8 decimals
>
> 3. Now the `refPrice` will be returned in `quoteDecimal`; which is 18 decimals.
>
> - So as can be noticed; if the `_cloPriceInQuote` returned price is consumed by the `WooPPV2` contract, then the price decimals are 18 not 8 decimals!

Could you please have a second look and re-evaluate the issue?
Thanks!

**Comment by sherlock-admin2** [comment]
> Escalate
> this issue has been misjudged as it seesms clearly fromt the judge [comment](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/90#:~:text=WangAudit%20commented%3A,denominated%20in%20USD):
> > WangAudit commented:
> the decimals are set according to the chainlink's price feed (you can see in the function setQuoteToken) therefore; it will be indeed 8 decimals cause chainlinks price feeds have 8 decimals if denominated in USD
> 
> while this issue has nothing to do with the chainlink price decimals but with the **assumption that the calculated quote price by `_cloPriceInQuote()` will be always of 8 decimals** (as the calculated price decimal is returned by [`decimals()`](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/wooracle/WooracleV2_2.sol#L263C5-L265C6) function) that is mistakenly assumed to be compatible with the used quote tokens on every chain, 
> 
> I am quoting the step-by-step illustration that was demonstrated by this issue [here](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/90#:~:text=But%20where%20exactly,not%208%20decimals!), where it had been clearly shown that the calculated price would be in different decimals than the assumed **8** decimals :
> > **But where exactly does the returned decimals() doesn't match the actual price decimal?**
> Let's look at the following example; knowing that the quote tokens are stable tokens such as USDC & USDT which have 6-decimals on some chains and 18 decimals on other chains (as in BNB smart chain):  
> >1. The `WooracleV2_2` is deployed on BNB smart chain, where we have [USDC](https://bscscan.com/token/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d) as the quote token with 18-decimals, and [Binance-Peg Ethereum Token-ETH](https://bscscan.com/token/0x2170ed0880ac9a755fd29b2688956bd959f933f8) as a base token with 18-decimals.
> >
> > 2. In `_cloPriceInQuote()` function:
>   > - the `quoteOracle` is `USDC / USD` data feed with price returned in 8 decimals
>   > - and the `baseOracle` is `ETH / USD` data feed with price returned in 8 decimals
> >
> > 3. Now the `refPrice` will be returned in `quoteDecimal`; which is 18 decimals.
> >
> > - So as can be noticed; if the `_cloPriceInQuote` returned price is consumed by the `WooPPV2` contract, then the price decimals are 18 not 8 decimals!
> 
> Could you please have a second look and re-evaluate the issue?
> Thanks!

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
As we can see `uint8 quoteDecimal = clOracles[_toToken].decimal;` Let's look at the `clOracles` [mapping](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/wooracle/WooracleV2_2.sol#L67C5-L67C51): `mapping(address => CLOracle) public clOracles;`

Now, let's look at the [CLOracle struct](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/wooracle/WooracleV2_2.sol#L60C5-L64C6): 
```
struct CLOracle {
        address oracle;
        uint8 decimal;
        bool cloPreferred;
    }
```

Now let's look at how we set up quote tokens' decimals in [`setQuoteToken`](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/wooracle/WooracleV2_2.sol#L103):

`cloRef.decimal = AggregatorV3Interface(_oracle).decimals();`

`AggregatorV3Interface` is the interface of Chainlink's Price Feeds and if we run `decimals` method on `AggregatorV3Interface` it returns Price Feed's decimals, not token's decimals.

Therefore, for all the tokens the decimals in `CLOracle` struct will 8, not 18 or any other number, since Chainlink's price feed denominated in USD are using 8 decimals (and they're used here). Therefore, the report is wrong and `uint8 quoteDecimal = clOracles[_toToken].decimal;` will return 8 decimals and not 18.

**Comment by DevHals** [comment]
Hi, I am not arguing about the used chainlink decimals!
the issue here is that  `WooracleV2_2.decimals()` is supposed to return the wooracle price decimals of base/quote tokens and not the chainlink price decimals!

let me break it down:
1. `WooracleV2_2.price()` is supposed to return **the price of the base token relative to the quote token** as indicated by `WooracleV2_2._cloPriceInQuote()` where  the returned `refPrice` is calulated as follows:
  ```javascript
  (, int256 rawBaseRefPrice, , uint256 baseUpdatedAt, ) = AggregatorV3Interface(baseOracle).latestRoundData();
          (, int256 rawQuoteRefPrice, , uint256 quoteUpdatedAt, ) = AggregatorV3Interface(quoteOracle).latestRoundData();
          uint256 baseRefPrice = uint256(rawBaseRefPrice);
          uint256 quoteRefPrice = uint256(rawQuoteRefPrice);
  
          // NOTE: Assume wooracle token decimal is same as chainlink token decimal.
          uint256 ceoff = uint256(10)**quoteDecimal;
          refPrice = (baseRefPrice * ceoff) / quoteRefPrice;
  ```
2. the `WooracleV2_2.decimals()` is supposed to return the decimals of the base/quote token price and **not the chainlink decimals**, but this function returns a hardcoded decimals of 8 (the comment above the function indicates that the decimals are for the base token, while this is not true as I have illustrated in my issue):
  ```javascript
    function decimals(address) external pure override returns (uint8) {
          return 8;
      }
  ```
3. quoting part of my previous reply to further explain the issue:
> **But where exactly does the returned decimals() doesn't match the actual price decimal?**
Let's look at the following example; knowing that the quote tokens are stable tokens such as USDC & USDT which have 6-decimals on some chains and 18 decimals on other chains (as in BNB smart chain):
>
>1. The `WooracleV2_2` is deployed on BNB smart chain, where we have [USDC](https://bscscan.com/token/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d) as the quote token with 18-decimals, and [Binance-Peg Ethereum Token-ETH](https://bscscan.com/token/0x2170ed0880ac9a755fd29b2688956bd959f933f8) as a base token with 18-decimals.
>
>2. In `_cloPriceInQuote()` function:
>
> - the `quoteOracle` is `USDC / USD` data feed with price returned in 8 decimals
> - and the `baseOracle` is `ETH / USD` data feed with price returned in 8 decimals
>
>3. Now the `refPrice` will be returned in `quoteDecimal`; which is 18 decimals.
>
>- So as can be noticed; if the `_cloPriceInQuote` returned price is consumed by the `WooPPV2` contract, then the price decimals are 18 not 8 decimals!

**Comment by WangSecurity** [comment]
As I've said above, `quoteDecimal` will return 8, not 18 decimals. I've already explained why above in the previous comment. `quoteDecimal` does NOT represent the actual decimal amount of the token. It represents decimal number of the chainlink price feed.

Therefore, let's look at this:
```
        uint256 baseRefPrice = uint256(rawBaseRefPrice);
        uint256 quoteRefPrice = uint256(rawQuoteRefPrice);

        // NOTE: Assume wooracle token decimal is same as chainlink token decimal.
        uint256 ceoff = uint256(10)**quoteDecimal;
        refPrice = (baseRefPrice * ceoff) / quoteRefPrice;
```

`baseRefPrice` and `quoteRefPrice` both have 8 decimals since it's the price from chainlink price feed. `quoteDecimal` also returns 8, since it uses the decimal number of the chainlink price feed (explained in the previous comment).
Therefore, `ceoff = 10**8 = 1e8`.
For example, let's pretend that both `baseRefPrice` and `quoteRefPrice` are 1 dollar, therefore, they're both 1e8 (cause it's from chainlink price feed, hence 8 decimals).

`refPrice = (1e8 * 1e8) / 1e8 = 1e16 / 1e8 = 1e8`. Simple math, `refPrice` have 8 decimals, not 18. And I want to highlight that `WooracleV2_2.decimals()` is not even used anywhere here.

**Comment by Czar102** [comment]
@DevHals do you agree with the above?

I'm planning to reject the escalation and leave the issue as is.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [DevHals](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/90/#issuecomment-2040837473): rejected
